name: GA viral

on:
  workflow_dispatch:
  schedule:
    - cron: '1 15 * * 0'   # 필요시 동일/별도

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python GA_cafe24pro_data_for_viral_paid_youtube.py
