name: Run Python automatically

on:
  schedule:
    - cron: '0 22 * * 0'  # 매주 월요일 오전 7시 (한국 기준)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run script
        run: python main.py
