name: Run Python automatically

on:
  schedule:
    - cron: '0 0 * * 1'   # 매주 월요일 0시 (UTC, 한국은 월요일 오전 9시)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run script
        run: python main.py
