name: Run Python automatically

on:
  schedule:
    - cron: '1 15 * * 0'   # 일요일 15:01 UTC = 월요일 00:01 KST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run script
        run: python main.py
