name: Run GA_cafe24pro_data

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - GA_cafe24pro_data.py
      - .github/workflows/run-ga.yml
  schedule:
    - cron: '1 15 * * 0'   # 매주 일요일 00:01 KST (UTC 15:01)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 pandas

      - name: Write credentials from secrets
        run: |
          echo "${{ secrets.GA_CLIENT_SECRET_JSON }}" > ./client_secret.json
          echo "${{ secrets.GA_TOKEN_JSON }}" > ./ga_token.json

      - name: Sanity check
        run: ls -la

      - name: Run GA script
        run: python GA_cafe24pro_data.py
